name: web5_flutter
description: "Flutter plugin for Web5"
version: 0.1.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  web5:
    git:
      url: https://github.com/TBD54566975/web5-dart.git
      path: packages/web5
      ref: main

  plugin_platform_interface: ^2.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.2

flutter:
  plugin:
    platforms:
      android:
        package: xyz.block.web5_flutter
        pluginClass: Web5FlutterPlugin
      ios:
        pluginClass: Web5FlutterPlugin
