name: tbdex
description: Dart library for TBDex API.
version: 0.1.0
repository: https://github.com/TBD54566975/tbdex-dart

environment:
  sdk: ^3.1.4

dependencies:
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
